name: Daily Human Traffic
on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours automatically
  workflow_dispatch: # Allows you to press "Play" manually

jobs:
  run-downloads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python script.py
